"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import "./globals.css";
type Question={id:string;year:number;title:string;category:string;level:string;note:string};
type Record={resource_id:string;score:number;status:string};
export default function Home(){
 const [questions,setQuestions]=useState<Question[]>([]),[records,setRecords]=useState<Record[]>([]),[active,setActive]=useState<Question|null>(null),[uploading,setUploading]=useState(false);
 const load=()=>fetch("/api/data").then(x=>x.json()).then(x=>{setQuestions(x.resources);setRecords(x.records)});
 useEffect(()=>{load()},[]);
 const average=records.length?Math.round(records.reduce((a,x)=>a+x.score,0)/records.length):0;
 const ability=useMemo(()=>[...new Set(questions.map(x=>x.category))].map(category=>{const ids=new Set(questions.filter(x=>x.category===category).map(x=>x.id)),rs=records.filter(x=>ids.has(x.resource_id)),score=rs.length?Math.round(rs.reduce((a,x)=>a+x.score,0)/rs.length):0;return{category,n:ids.size,score}}),[questions,records]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await fetch("/api/data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resourceId:active!.id,score:+f.get("score")!,minutes:+f.get("minutes")!,status:f.get("status"),notes:f.get("notes")})});setActive(null);load()}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();await fetch("/api/upload",{method:"POST",body:new FormData(e.currentTarget)});setUploading(false);load()}
 async function reset(){if(!window.confirm("確定清除全部練習紀錄？此動作只會清除成績、耗時與筆記，題庫會保留。"))return;await fetch("/api/data",{method:"DELETE"});load()}
 async function removeQuestion(id:string,title:string){if(!window.confirm(`確定刪除「${title}」？題檔與此題練習紀錄都會一併刪除。`))return;await fetch(`/api/question/${id}`,{method:"DELETE"});load()}
 return <main><header><div><p>工科賽・電腦軟體設計</p><h1>冠軍訓練平台</h1><small>永久題庫・模擬紀錄・能力地圖</small></div><button onClick={()=>setUploading(true)}>＋ 上傳題目</button></header>
 <section className="metrics"><b>題庫 <strong>{questions.length}</strong></b><b>完成練習 <strong>{records.filter(x=>x.status==="完成").length}</strong></b><b>平均分數 <strong>{records.length?average:"—"}</strong></b><b>本週建議 <strong>{!records.length?"先做基線":average<70?"補基本盤":"挑戰核心題"}</strong></b></section>
 <section><p className="kicker">題庫與模擬</p><h2>選題後直接進入作答工作區</h2><div className="grid">{questions.map(x=><article key={x.id}><div><em>{x.year}</em><span>{x.level}</span></div><h3>{x.title}</h3><p>{x.note}</p><footer>{/^\d{3}-\d+$/.test(x.id)&&<a className="practice-link" href={`/practice/${x.id}`}>進入作答工作區</a>}<a href={`/question/${x.id}`}>閱讀題目</a><button onClick={()=>setActive(x)}>回填練習</button>{!/^\d{3}-\d+$/.test(x.id)&&<button className="delete" onClick={()=>removeQuestion(x.id,x.title)}>刪除題目</button>}</footer></article>)}</div></section>
 <section className="map"><p className="kicker">能力地圖</p><div className="maphead"><h2>用實戰紀錄決定下週優先補強項目</h2>{records.length>0&&<button className="delete" onClick={reset}>重設練習紀錄</button>}</div><div className="mapgrid">{ability.map(x=><article key={x.category}><div><b>{x.category}</b><strong>{x.score||"—"}</strong></div><i><u style={{width:`${x.score}%`}}/></i><small>{x.n} 題 · {!x.score?"尚未測量":x.score<70?"下週優先補強":x.score<85?"維持練習":"可提高難度"}</small></article>)}</div></section>
 {active&&<div className="modal" onClick={()=>setActive(null)}><form onSubmit={save} onClick={e=>e.stopPropagation()}><button type="button" onClick={()=>setActive(null)} aria-label="取消並關閉">×</button><p className="kicker">完成後回填</p><h2>{active.title}</h2><label>結果<select name="status"><option>完成</option><option>部分完成</option><option>未完成</option></select></label><label>分數<input name="score" type="number" min="0" max="100" required/></label><label>耗時（分）<input name="minutes" type="number" min="1" required/></label><label>筆記<textarea name="notes"/></label><button>儲存</button></form></div>}
 {uploading&&<div className="modal" onClick={()=>setUploading(false)}><form onSubmit={add} onClick={e=>e.stopPropagation()}><button type="button" onClick={()=>setUploading(false)} aria-label="取消並關閉">×</button><p className="kicker">題庫擴充</p><h2>上傳題目</h2><label>名稱<input name="title" required/></label><label>年度<input name="year" type="number" required/></label><label>分類<input name="category" required/></label><label>難度<select name="level"><option>保底</option><option>核心</option><option>整合</option></select></label><label>摘要<textarea name="note"/></label><label>題目檔<input name="file" type="file" accept="application/pdf" required/></label><button>上傳</button></form></div>}</main>
}
